package ca.mcgill.ecse428.ESCAPE.service;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

import ca.mcgill.ecse428.ESCAPE.dto.EventRequestDto;
import ca.mcgill.ecse428.ESCAPE.dto.EventResponseDto;
import ca.mcgill.ecse428.ESCAPE.exception.EventException;
import ca.mcgill.ecse428.ESCAPE.model.Event;
import ca.mcgill.ecse428.ESCAPE.model.UserProfile;
import ca.mcgill.ecse428.ESCAPE.repository.EventRepository;

@Service
public class EventService {
    private final EventRepository eventRepository;
    //private final UserProfileRepository userProfileRepository;

    @Autowired
    public EventService(EventRepository eventRepository) {
        this.eventRepository = eventRepository;
    }

    public Iterable<Event> getAllEvents() {
        return eventRepository.findAll();
    }

    public Event getEventById(int id) throws EventException {
        Event event = eventRepository.findEventById(id);
        if (event != null) {
            return event;
        } else {
            throw new EventException(HttpStatus.NOT_FOUND, "Event not found.");
        }
    }

    // TO DO implement autogenerated IDs, also add user profile when the repo is made
    public EventResponseDto createEvent(EventRequestDto request) {
    	UserProfile creator = null;
    	//creator = UserProfileRepository.getUserProfileById(request.getUserId());
    	Event event = new Event(request.getName(), request.getDescription(), request.getTicketPrice(), 0, creator);
    	eventRepository.save(event);
    	return new EventResponseDto(event);
    }

    public void updateEvent(int id, Event event) throws EventException {
        Event optionalEvent = eventRepository.findEventById(id);
        if (optionalEvent != null) {
            event.setEventId(id);
            eventRepository.save(event);
        } else {
            throw new EventException(HttpStatus.NOT_FOUND, "Event not found.");
        }
    }

    public void deleteEvent(int id) throws EventException {
        Event event = eventRepository.findEventById(id);
        if (event != null) {
            eventRepository.delete(event);
        } else {
            throw new EventException(HttpStatus.NOT_FOUND, "Event not found.");
        }
    }
}